
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 14 15:48:43 COT 2023
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_decremento = 40;
  public static final int Return = 56;
  public static final int Comillas_s = 53;
  public static final int Llave_c = 60;
  public static final int Llave_a = 59;
  public static final int Std = 68;
  public static final int Back = 11;
  public static final int Linea = 2;
  public static final int Break = 10;
  public static final int Coma = 50;
  public static final int Parent_c = 58;
  public static final int Parent_a = 57;
  public static final int Corchete_c = 62;
  public static final int Op_asigResta = 41;
  public static final int Corchete_a = 61;
  public static final int T_long = 15;
  public static final int Punto = 49;
  public static final int Default = 76;
  public static final int T_char = 16;
  public static final int Op_diferente = 27;
  public static final int Op_desIzq = 47;
  public static final int For = 7;
  public static final int Void = 63;
  public static final int Else = 4;
  public static final int Resta = 22;
  public static final int Op_and = 31;
  public static final int Cin = 55;
  public static final int Suma = 21;
  public static final int Using = 65;
  public static final int ERROR = 75;
  public static final int Op_mayor = 29;
  public static final int Op_asigDiv = 42;
  public static final int Cadena = 12;
  public static final int Op_orB = 34;
  public static final int Main = 64;
  public static final int Do = 5;
  public static final int Op_or = 30;
  public static final int P_coma = 48;
  public static final int Scanf = 71;
  public static final int Case = 9;
  public static final int T_float = 17;
  public static final int T_byte = 18;
  public static final int Op_not = 36;
  public static final int If = 3;
  public static final int Define = 72;
  public static final int EOF = 0;
  public static final int Op_igual = 26;
  public static final int T_bool = 19;
  public static final int Cout = 54;
  public static final int Numero = 74;
  public static final int Division = 24;
  public static final int Op_desDer = 46;
  public static final int Op_asigModulo = 45;
  public static final int Namespace = 66;
  public static final int error = 1;
  public static final int Op_menor = 28;
  public static final int Comillas = 52;
  public static final int Op_menorE = 32;
  public static final int Op_mayorE = 33;
  public static final int Iostream = 67;
  public static final int Identificador = 69;
  public static final int Op_asigMult = 43;
  public static final int Op_incremento = 39;
  public static final int Op_boolFalse = 37;
  public static final int Include = 73;
  public static final int DPuntos = 51;
  public static final int Modulo = 25;
  public static final int T_int = 13;
  public static final int Printf = 70;
  public static final int T_double = 14;
  public static final int Op_andB = 35;
  public static final int Op_boolTrue = 38;
  public static final int Op_asigSuma = 44;
  public static final int Igual = 20;
  public static final int While = 6;
  public static final int Multiplicacion = 23;
  public static final int Switch = 8;
}

